apiVersion: v2
name: helmchart
type: application
description: A Helm chart for Kubernetes
version: 1.0.1
appVersion: 1.0.1
icon: https://raw.githubusercontent.com/clouddrove/helmchart/feat/github-action/images/helm.png
keywords:
  - helm
  - chart
  - k8s
  - helm-chart
home: https://github.com/clouddrove/helmchart
maintainers:
  - name: CloudDrove Inc
    email: hello@clouddrove.com
