apiVersion: v2
name: cloudflare-ddns
description: Cloudflare DDNS updater
type: application
version: 0.1.1
appVersion: "1"
sources:
  - https://github.com/favonia/cloudflare-ddns
keywords:
    - helm
    - chart  
    - k8s
    - cloudflare
    - cloudflare-ddns
home: https://github.com/clouddrove/helmchart
maintainers:
    - name: CloudDrove Inc
      email: hello@clouddrove.com
