replicaCount: 1

image:
  repository: favonia/cloudflare-ddns
  tag: "1"
  pullPolicy: IfNotPresent

imagePullSecrets: []

podAnnotations: {}
podLabels: {}

serviceAccount:
  name: ""                # Provide existing ServiceAccount name to use (leave empty to create one)

secret:
  name: ""                # Provide existing Secret name to use (leave empty to create one)
  key: api-token          # (Required) Will become the key of new Secret. If using an existing Secret, this key must already exist.
  value: ""               # Will become the Value for the above key (required if creating a Secret, i.e. when name is empty)

env:
  domains: "example.com"  # REQUIRED: comma-separated list
  proxied: true
  ttl: ""                 # optional; "" => Cloudflare auto
  recordComment: ""       # optional
  ip4Provider: ""
  ip6Provider: ""

hostNetwork: false
dnsPolicy: ClusterFirst   # Optional; ignored when hostNetwork=true (ClusterFirstWithHostNet is used instead)


configmap:
  enabled: false           # Set to true to create a ConfigMap with additional environment variables
  name: ""                 # Optional: specify a custom ConfigMap name (defaults to release fullname)
  configs: {}              # Optional: key-value pairs to be added to the ConfigMap

resources:
   requests:
     cpu: 10m
     memory: 32Mi
   limits:
     memory: 128Mi

securityContext:
   runAsUser: 1000
   runAsGroup: 1000
   readOnlyRootFilesystem: true
   allowPrivilegeEscalation: false
   capabilities:
     drop: ["ALL"]

affinity: {}

nodeSelector: {}

tolerations: []
