{{- if and .Values.secretEnv (not .Values.existingSecret) }}
{{- $secretData := dict }}
{{- range $key, $value := .Values.secretEnv }}
  {{- if and $value (ne (toString $value) "") }}
    {{- $_ := set $secretData $key $value }}
  {{- end }}
{{- end }}
{{- if $secretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "safio.fullname" . }}-secret
  labels:
    {{- include "safio.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
