apiVersion: v2
name: hrbuddy
description: A Helm chart for Hrbuddy - AI-Powered HR Knowledge Assistant
type: application
version: 0.1.1
appVersion: "1.0.0"
keywords:
  - hr
  - slack
  - ai
  - rag
  - knowledge-base
home: https://github.com/clouddrove/hrbuddy
maintainers:
  - name: CloudDrove
sources:
  - https://github.com/clouddrove/hrbuddy
