{{- with .Values.members }}
{{- range $i, $u := . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "sa-%s-token" $u.name | quote }}
  namespace: {{ $u.namespace | default (printf "ns-%s" $u.name) | quote }}
  annotations:
    kubernetes.io/service-account.name: {{ printf "sa-%s" $u.name | quote }}
  labels:
    {{- include "rbac.labels" $ | nindent 4 }}
type: kubernetes.io/service-account-token
---
{{- end }}
{{- end }}
