apiVersion: v2
name: adrija
description: A Helm chart for Adrija - AI Assistant for Slack
type: application
version: 0.2.1
appVersion: "1.0.1"
keywords:
  - slack
  - ai
  - chatbot
  - assistant
maintainers:
  - name: CloudWizz
home: https://github.com/cloudwizz/adrija
sources:
  - https://github.com/cloudwizz/adrija
