{{- if and .Values.secret.enabled (not .Values.secret.existingSecret) }}
{{- $secretName := printf "%s-secret" (include "helmchart.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "helmchart.namespace" . }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 }}
type: Opaque
data:
  TUNNEL_TOKEN: {{ .Values.secret.token | b64enc | quote }}
{{- end }}
