{{- if and .Values.secret.value (not .Values.secret.existingSecret) }}
{{- $secretName := default (include "cloudflare-ddns.fullname" .) .Values.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "cloudflare-ddns.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.key }}: {{ .Values.secret.value | quote }}
{{- end }}
