apiVersion: v2
appVersion: 1.0.1
description: A Helm chart for Kubernetes
home: https://github.com/clouddrove/vigil
icon: https://github.com/clouddrove/helmchart/blob/feat/github-action/images/vigil.png
keywords:
- helm
- chart
- k8s
- helm-chart
maintainers:
- email: hello@clouddrove.com
  name: Clouddrove Inc
name: vigil
type: application
version: 1.0.1
