{{- if and (not .Values.existingSecret) .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "relaybot.secretName" . }}
  labels:
    {{- include "relaybot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "relaybot.clientSlackTokenKey" . }}: {{ .Values.secrets.clientSlackToken | quote }}
  {{ include "relaybot.personalSlackTokenKey" . }}: {{ .Values.secrets.personalSlackToken | quote }}
{{- end }}
