{{- if and .Values.rbac.enabled .Values.rbac.clusterRoleBinding.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helmchart.fullname" . }}-clusterrolebinding
  namespace: {{ include "helmchart.namespace" . }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
subjects:
  {{- if and .Values.rbac.clusterRoleBinding.users.enabled (gt (len .Values.rbac.clusterRoleBinding.users.list) 0) }}
  {{- range .Values.rbac.clusterRoleBinding.users.list }}
  - kind: User
    name: {{ . }}
    apiGroup: rbac.authorization.k8s.io
  {{- end }}
  {{- end }}

  {{- if and .Values.rbac.clusterRoleBinding.groups.enabled (gt (len .Values.rbac.clusterRoleBinding.groups.list) 0) }}
  {{- range .Values.rbac.clusterRoleBinding.groups.list }}
  - kind: Group
    name: {{ . }}
    apiGroup: rbac.authorization.k8s.io
  {{- end }}
  {{- end }}

roleRef:
  kind: ClusterRole
  name: {{ include "helmchart.fullname" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end }}
