{{- if and .Values.statefulset.enabled .Values.statefulset.secret.enabled (not .Values.statefulset.secret.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helmchart.fullname" . }}-sts-secret
  namespace: {{ include "helmchart.namespace" . }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
    usedBy: {{ include "helmchart.fullname" . }}-sts
type: Opaque
stringData:
{{- range $k, $v := .Values.statefulset.secret.secrets }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
