{{- if and .Values.daemonset.enabled .Values.daemonset.secret.enabled (not .Values.daemonset.secret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helmchart.fullname" . }}-ds-secret
  namespace: {{ include "helmchart.namespace" . }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
    usedBy: {{ include "helmchart.fullname" . }}-ds
type: Opaque
stringData:
{{- range $k, $v := .Values.daemonset.secret.secrets }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
