{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "helmchart.fullname" . }}-vpa
  namespace: {{ include "helmchart.namespace" . }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: {{ default "Deployment" .Values.vpa.targetKind }}
    name: {{ include "helmchart.fullname" . }}

  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}

  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Values.vpa.containerName | quote }}
        {{- if .Values.vpa.controlledResources }}
        controlledResources:
          {{- toYaml .Values.vpa.controlledResources | nindent 10 }}
        {{- end }}
        {{- if .Values.vpa.minAllowed }}
        minAllowed:
          {{- toYaml .Values.vpa.minAllowed | nindent 10 }}
        {{- end }}
        {{- if .Values.vpa.maxAllowed }}
        maxAllowed:
          {{- toYaml .Values.vpa.maxAllowed | nindent 10 }}
        {{- end }}
        {{- if .Values.vpa.controlledValues }}
        controlledValues: {{ .Values.vpa.controlledValues | quote }}
        {{- end }}
{{- end }}
