{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "pass2gh.fullname" .) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "pass2gh.labels" . | nindent 4 }}
{{- end }}

