name: Helm Drift Detection

on:
  workflow_dispatch:
    inputs:
      kubeconfig:
        description: "Base64 encoded kubeconfig of the target cluster"
        required: true
        type: string
      provider:
        description: "Cloud provider (e.g., aws)"
        required: false
        default: "aws"
        type: string
      aws_region:
        description: "AWS region (required if provider=aws)"
        required: false
        default: "us-east-1"
        type: string
      role-duration-seconds:
        description: "Session duration when assuming role"
        required: false
        default: "3600"
        type: string
  push:
    branches:
      - master

jobs:
  drift-detect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      
      # Install kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      # Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: "latest"

      - name: üîß Configure AWS credentials
        if: ${{ inputs.provider == 'aws' }}
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          role-to-assume: ${{ secrets.BUILD_ROLE }}
          aws-region: ${{ inputs.aws_region }}
          role-duration-seconds: ${{ inputs.role-duration-seconds }}
          role-skip-session-tagging: true

      - name: Install Helm Drift Plugin
        run: |
          git clone https://github.com/nikhilsbhat/helm-drift.git
          pwd
          helm plugin install ./helm-drift/.
          helm plugin list

      - name: Configure kubeconfig
        run: |
          # Use input if provided, otherwise fallback to GitHub secret
          KUBECONFIG_B64="${{ inputs.kubeconfig || secrets.CLUSTER_KUBECONFIG }}"
          echo "$KUBECONFIG_B64" | base64 -d > $HOME/.kube/config
          kubectl cluster-info
  
      - name: Detect Drift
        run: |
          export PATH="/usr/local/bin:$PATH"
          export KUBECTL_BIN=/usr/local/bin/kubectl
          
          echo "Using kubectl at $(which kubectl)"
          kubectl version --client=true --output=yaml
          
          echo "üîç Checking for Helm drift..."
          helm drift all
          
          if [ "$drifts" -gt 0 ]; then
            echo "‚ùå Drift detected!"
            exit 1
          else
            echo "‚úÖ No drift detected."
          fi
